eval/python/evaluate.py
- using sys.version_info to be backwards compatible
- map is now lazy
- range does what xrange did before
- tested changes with 2.7, 3.4 and 3.5 (shouldn't matter)
=> Fixed several Python 3 compatibility problems

src/glove.c
Memory was allocated without space for biases. As the result of this some gradients were overwritten by weights, and some costs were overwritten by gradients.
You can see below that word vector positions inside W are calculated with additional space for bias (`+ 1`), for example:
```C
/* Get location of words in W & gradsq */
l1 = (cr.word1 - 1LL) * (vector_size + 1); // cr word indices start at 1
l2 = ((cr.word2 - 1LL) + vocab_size) * (vector_size + 1); // shift by vocab_size to get separate vectors for context words
```
Thus the memory allocation must also use additional space.
With this fix applied the algorithm tends to perform slightly better on provided analogy tests.
=> Fixed memory allocation bugs: no space for biases

src/shuffle.c
shuffle accesses array at index n+1, so the passed n should be i-2 like a few lines above
=> fixed shuffle call to obey array boundaries

src/glove.c
See https://github.com/stanfordnlp/GloVe/issues/8 for discussion.
=> Fixed double free or corruption bug.

src/cooccur.c
_cooccur_ introduces all-0 record(s) if one of the chunks it tries to write is empty; this can happen if the vocabulary is small (17 in my case). This PR fixes that.
Note that I haven't checked if a small vocabulary introduces other errors.
=> Length check in write_chunk().

eval/python/evaluate.py
Small fix in in-line comments:`eval/python/evaluate.py` is normalizing the norm of the word vectors and not their variance as indicated in the in-line comments.
=> Fix misleading comment regarding normalization of vectors

src/cooccur.c
I am using GloVe in a context where the order of the tokens and distances between tokens in the context window don't have the same meaning as in most language modeling tasks. Just counting the unweighted cooccurrences leads to more meaningful vectors in some contexts. In the proposed change I am adding an argument in cooccur.c to take a flag to ignore distance between words when counting coocurrences. 
The default behavior remains the same as before, so an explicit flag needs to be passed to switch on the new behavior.
=> Added the option to not weight cooccurrence counts by word distance

src/README.md
GloVe supports documents separated by new line characters (\n) in corpus. Inserting multiple "dummy" words to separate documents is not necessary.
Detecting line feeds (\n) is done in function `get_word` in cooccur.c.
=> Fixed misleading README.md about inserting "dummy" words between documents in corpus

src/glove.c
I passed a directory as the `-vocab-file` argument, which apparently doesn't trigger an error from `fopen`. This led to `vocab_size = 0`, which caused a segfault during execution.
I've raised an error if the vocab size is still 0 after trying to read the vocab file. This seems a bit better than checking for a directory, since we still should raise if an incorrect but existing file path was passed.
The PR should still be useful in addition to #138, as that PR only checks the status from `fread`.
=> Raise error if no vocab entries found

Makefile, src/glove.c
This PR fixes two issues with NaNs during training.
First, the checks for NaNs in glove.c did not work with compiler options from the Makefile.
-Ofast disables checks for NaNs and +-Infs. Changed to -O3 by default, so that users at least see the error messages during training.
Second, default learning rate causes on some data exploding gradients, and, as a result, +-Infs and NaNs. People on the internet recommend lowering learning rate in such a case, but this solution is not perfect (users have to get NaNs in their embeddings, then to google for a solution, then train again).
Now, there is a gradient components clipping parameter with a reasonable default which allows training with arbitrary initial learning rates (including default) on arbitrary data out of the box, and no fiddling is …
=> Fix nan during training

src/glove.c
I made some code changes to fix #170.
I created two new parameters, `-init-gradsq-file` and `-load-init-gradsq` that correspond to `-init-param-file` and `-load-init-param`. Most of the code between the two sets of parameters is exactly the same.
=> Add options for loading initial squared gradients

src/glove.c
I think this is a typo mistake. And it may cause exception if `W_updates2` is NULL
=> fix: fix typo

eval/python/word_analogy.py
Hey! 
I'm I noticed that the `eval/python/word_analogies.py` used `raw_input` to read from stdin. 
In python 3+  `raw_input` was replaced with just `input` (See [PEP 3111](https://www.python.org/dev/peps/pep-3111/) and [What’s New In Python 3.0](https://docs.python.org/3/whatsnew/3.0.html#builtins))
So I made it compatible with python3 and python2. 
Cheers : )
=> Modifications in the eval/python/word_analogies to support Python 3+

Makefile
The build error I got without this patch:
% make
mkdir -p build
gcc -c src/vocab_count.c -o build/vocab_count.o -lm -pthread -O3 -march=native -funroll-loops -Wall -Wextra -Wpedantic
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
clang: error: the clang compiler does not support '-march=native'
make: *** [build/vocab_count.o] Error 1
=> Fix building on macOS/Apple Silicon

.gitignore
They're a bit annoying when working with the repository because they keep appearing in git status output etc.
=> Gitignore some files produced by demo.sh

src/cooccur.c
The current implementation using an 'int' runs into an overflow when specifying 256G of memory.
This patch fixed the problem changing the 'int' into a 'long long'.
Fixes: #215
=> Fixed overflow_threshold overflow when using 256G of memory

src/glove.c
Fixes: https://github.com/stanfordnlp/GloVe/issues/172
=> Make check-nan static to resolve undefined reference to check_nan

src/glove.c
It would be helpful to be able to use the word vectors and context vectors separately in some applications. In particular, per Levy, Goldberg & Dagan ("Improving distributional similarity with lessons learned from word embeddings", 2015 TACL; https://doi.org/10.1162/tacl_a_00134), the angle between a word vector and a context vectors has a different meaning than the angle between two word vectors, and users may wish to differentiate between these depending on what they are trying to do.
The .txt output option in glove.c is modified to allow setting model=3; this setting row-concatenates the context vectors rather than adding them to the word vectors. Perhaps it's preferable to either column-concatenate or save the context vectors to a separate file? If there is sufficient interest, I'm …
=> Allow glove.c to output context vectors

src/shuffle.c
This PR fixes a subtle off-by-one bug in src/shuffle.c where the shuffling function was consistently called with an incorrect element count. This resulted in the last one or two records of every processed chunk being excluded from the shuffle, leading to a less-than-perfectly random shuffle.
The shuffle() function expects the second argument (n) to be the total number of elements in the array to shuffle. However, it was being called in three places with i-2 or i-1 instead of i, where i represents the correct count of elements in the buffer.
In shuffle_by_chunks() (main loop): shuffle(array, i-2) was used, excluding the last two elements of every full chunk from being shuffled.
In shuffle_by_chunks() (final chunk): shuffle(array, i-2) was used, similarly affecting the final chunk.
In …
=> Fix(shuffle): Correct off-by-one errors in shuffle calls

eval/python/distance.py, eval/python/word_analogy.py
**Issue:** Evaluation scripts crashed with NumPy 2.0 due to the removal of `np.Inf`.
**Fix:** Replaced `np.Inf` with `np.inf` for compatibility.
=> Fix AttributeError: np.Inf removed in NumPy 2.0. Use np.inf instead.

Makefile, src/common.c, src/common.h, src/cooccur.c, src/glove.c, src/shuffle.c, src/vocab_count.c
This pull request addresses two issues to improve the C build system:
1. C Code Compiler Warning Fixes
Issue: Compiling the C source produced -Wstrict-prototypes warnings on modern compilers.
Fix: Modernized C function declarations to use (void) instead of () for functions with no arguments, which is the correct syntax.
2. Makefile Build Process Improvement
Issue: The build process produced warnings about unused linker flags (-lm) during the compilation stage.
Fix: Refactored the Makefile to separate compiler flags (CFLAGS) from linker libraries (LDLIBS), applying -lm only during the final linking stage. This cleans up the build output and follows standard Makefile practices.
Supersedes #228
=> Build: Improve Makefile and fix C compiler warnings
